version: '3.1'

services:
  wordpress:
    image: wordpress:php7.4
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: db4wp
      WORDPRESS_TABLE_PREFIX: wp23o8z4hb_
    volumes:
      - ./:/var/www/html/wp-content/plugins/cables-wpplugin
      - ./docker/docker_php_config.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker/htaccess:/var/www/html/.htaccess
  wordpress_db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: db4wp
      MYSQL_DATABASE: wordpress
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: db4wp