version: "3"

services:
  wordpress:
    image: wordpress:php7.3
    links:
      - wordpress_db:mysql
    ports:
      - 8082:80
    depends_on:
      - wordpress_db
    environment:
      WORDPRESS_DB_PASSWORD: db4wp
    networks:
      - cables_wordpress_network
  wordpress_db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: db4wp
    networks:
      - cables_wordpress_network

networks:
 cables_wordpress_network:
    driver: "bridge"