environment: dev
global:
  cables_url: https://cables.gl
  cables_api_url: https://cables.gl/api
  default_language: en
dev:
  cables_url: https://dev.cables.gl
  cables_api_url: https://dev.cables.gl/api
local:
  cables_url: http://frontend:3000
  cables_api_url: http://api:3000/api/v1